apiVersion: "v1"
kind: Pod
metadata:
  name: redis
  labels:
    app: redis
    type: db
spec:
  containers:
  - name: redis
    image: redis:latest
    resources:
      limits:
        memory: "525Mi"
        cpu: "525m"
    ports:
      - containerPort: 6379
        protocol: TCP
