---
environment:
  - "discovery.type=single-node"
# Permit co-located instances for solitary minikube virtual machines.
antiAffinity: "soft"
minimumMasterNodes: 1

spec: 
  replicas: 1

# Shrink default JVM heap.
esJavaOpts: "-Xmx128m -Xms128m"

# Allocate smaller chunks of memory per pod.
resources:
  requests:
    cpu: "100m"
    memory: "212M"
  limits:
    cpu: "100m"
    memory: "212M"

# Request smaller persistent volumes.
volumeClaimTemplate:
  accessModes: [ "ReadWriteOnce" ]
  storageClassName: "hostpath"
  resources:
    requests:
      storage: 100M