apiVersion: v1
kind: Service
metadata:
  name: product-service
spec:
  selector:
    app: product-service
    type: back-end
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 80  
---
apiVersion: v1
kind: Service
metadata:
  name: website
spec:
  selector:
    app: website
    type: front-end
  type: NodePort
  ports:
  - port: 5000
    targetPort: 80
    protocol: TCP

